### PR TITLE
Fix bug, add type 'str' decoding

### PR DESCRIPTION
**Pull request by ydkhatri**
Added decoding for 'str' type, just converts bytes to str.
Also removed conversion of bytes to string in `decode_varint()` and `decode_uvarint()`. Perhaps this was there for python2, but on python3 this will not work and is not needed.

### CODE REVIEW

**Comment by rwinkelmaier-ncc** [comment]
Thanks for submitting a patch. The library was definitely not design to work with Python 3 yet and has to maintain compatibility with Python 2 to be integrated with Burp. I'm working on putting together some more reproducible test cases for the library and Burp parts, then should be able to merge this in as well as work on some things like Python 3 support and other features.

**Comment by ydkhatri** [comment]
Thanks for responding. I and so many others are primarily just interested in the protobuf parsing part of this library. Do you have any plans to make this available on pypi for easy installation and integration into other foss projects? Or I can do this too. Once again, thanks for creating this library.

**Comment by rwinkelmaier-ncc** [comment]
Hi, sorry for the delay. Everything is a bit crazy nowadays. I've been focusing on implementing some testing so that I can iterate on changes faster without worrying about pushing broken changes as much and should be pushing those tests soon along with some dependency updates.

I'll merge in what I can ASAP, but do need to maintain compatibility with python2. I will focus on bringing everything up to python 2/3 compatibility next.

I would like to keep everything under the same repo and would like to own any pip deployment once the library is updated w/ the changes you need. There are some more changes down the line I would like to make to add on more features and make it more user friendly to work with. I will work on setting aside some time to be a little quicker with updates and any pull requests (testing will help a lot there).

**Comment by ydkhatri** [comment]
> I'll merge in what I can ASAP, but do need to maintain compatibility with python2. I will focus on bringing everything up to python 2/3 compatibility next.

Then this pull won't really help, since I removed python2 support. Also the following (newer) commits remove burp, since I don't need it. They got automatically pulled in here. I will close this pull then.

**Comment by rwinkelmaier-ncc** [comment]
I should be able to cherry-pick the main changes from the code, with some changes to ensure anything it decodes can be re-encoded. That shouldn't be too hard for the string type, but might need some changes for the bytes as hex. Probably would need to be implemented as it's own type. The flag could still be used to change the default type for binary fields.

Maintaining both python 2 and 3 support looks like it should be doable.

It may also be an option to push the library only as a separate branch.

**Pull request closed without merging**
